# - Optimizer: 'ADADELTA'
#   lr: 1.0
#   rho: 0.9
#   eps: 0.000001
#   weight_decay: 0
#   hidden_layer_width: 5
#   depth: 20
# - Optimizer: 'ADADELTA'
#   lr: 0.5
#   rho: 0.45
#   eps: 0.000002
#   weight_decay: 0.5
# - Optimizer: 'ADADELTA'
#   lr: 1.5
#   rho: 0.75
#   eps: 0.000003
#   weight_decay: 1
# - Optimizer: 'ADADELTA'
#   lr: 0.25
#   rho: 0.25
#   eps: 0.000004
#   weight_decay: 1.5
# - Optimizer: 'SGD'
#   lr: 0.001
#   momentum: 0.9
# - Optimizer: 'SGD'
#   lr: 0.002
#   momentum: 0.5
# - Optimizer: 'SGD'
#   lr: 0.003
#   momentum: 0.1
# - Optimizer: 'SGD'
#   lr: 0.005
#   momentum: 1.0
# - Optimizer: 'ADAM'
#   lr: 0.001
#   eps: 0.00000001
#   weight_decay: 0
#   amsgrad: False
#   foreach: False
#   maximize: False
#   fused: False
# - Optimizer: 'ADAM'
#   lr: 0.0005
#   eps: 0.00000002
#   weight_decay: 0.5
#   amsgrad: True
#   foreach: True
#   maximize: True
#   fused: False
# - Optimizer: 'ADAM'
#   lr: 0.0025
#   eps: 0.000000025
#   weight_decay: 1
#   amsgrad: True
#   foreach: True
#   maximize: False
#   fused: False
# - Optimizer: 'ADAM'
#   lr: 0.005
#   eps: 0.0000005
#   weight_decay: 2
#   amsgrad: False
#   foreach: False
#   maximize: True
#   fused: False
# - Optimizer: 'ADAGRAD'
#   lr: 0.01
#   lr_decay: 0
#   eps: 0.0000000001
#   weight_decay: 0
#   foreach: False
#   maximize: False
# - Optimizer: 'ADAGRAD'
#   lr: 0.005
#   lr_decay: 0.5
#   eps: 0.00000000005
#   weight_decay: 0.5
#   foreach: True
#   maximize: True
#   hidden_layer_width: 5
#   depth: 20
# - Optimizer: 'ADAGRAD'
#   lr: 0.05
#   lr_decay: 1
#   eps: 0.00000000025
#   weight_decay: 1
#   foreach: True
#   maximize: False
# - Optimizer: 'ADAGRAD'
#   lr: 0.1
#   lr_decay: 1
#   eps: 0.000000005
#   weight_decay: 1
#   foreach: False
#   maximize: True




